{
  "_from": "gitbook",
  "_id": "gitbook@3.2.3",
  "_inBundle": false,
  "_integrity": "sha512-vu7k5AKGj+sb//lJ4MZt+//0Bf9Sdz3zcCYdd7nGXvcIUCnZlMRylABju0fSp1OMHDj9WZo5CiCEqpaULEXu/A==",
  "_location": "/gitbook",
  "_phantomChildren": {
    "anymatch": "1.3.2",
    "async-each": "1.0.1",
    "aws4": "1.6.0",
    "boolbase": "1.0.0",
    "chalk": "1.1.3",
    "combined-stream": "1.0.5",
    "commander": "2.9.0",
    "core-util-is": "1.0.2",
    "depd": "1.1.2",
    "destroy": "1.0.4",
    "dom-serializer": "0.1.0",
    "domelementtype": "1.3.0",
    "entities": "1.1.1",
    "escape-html": "1.0.3",
    "extend": "3.0.1",
    "forever-agent": "0.6.1",
    "fsevents": "1.1.3",
    "glob-parent": "2.0.0",
    "htmlparser2": "3.8.3",
    "inherits": "2.0.3",
    "is-binary-path": "1.0.1",
    "is-glob": "2.0.1",
    "is-my-json-valid": "2.17.2",
    "is-typedarray": "1.0.0",
    "isarray": "1.0.0",
    "isstream": "0.1.2",
    "jsdom": "7.2.2",
    "json-stringify-safe": "5.0.1",
    "jsprim": "1.4.1",
    "mime-types": "2.1.17",
    "nth-check": "1.0.1",
    "oauth-sign": "0.8.2",
    "on-finished": "2.3.0",
    "path-is-absolute": "1.0.1",
    "pinkie-promise": "2.0.1",
    "process-nextick-args": "1.0.7",
    "readdirp": "2.1.0",
    "sshpk": "1.13.1",
    "stringstream": "0.0.5",
    "util-deprecate": "1.0.2"
  },
  "_requested": {
    "type": "tag",
    "registry": true,
    "raw": "gitbook",
    "name": "gitbook",
    "escapedName": "gitbook",
    "rawSpec": "",
    "saveSpec": null,
    "fetchSpec": "latest"
  },
  "_requiredBy": [
    "#USER",
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/gitbook/-/gitbook-3.2.3.tgz",
  "_shasum": "8c3043df0589e6f328f49c043002de56f3bc2046",
  "_spec": "gitbook",
  "_where": "/Users/nazimfaour",
  "author": {
    "name": "FriendCode Inc.",
    "email": "contact@gitbook.com"
  },
  "bin": {
    "gitbook": "./bin/gitbook.js"
  },
  "browser": "./lib/browser.js",
  "bugs": {
    "url": "https://github.com/GitbookIO/gitbook/issues"
  },
  "bundleDependencies": false,
  "contributors": [
    {
      "name": "Aaron O'Mullan",
      "email": "aaron@gitbook.com"
    },
    {
      "name": "Samy Pessé",
      "email": "samy@gitbook.com"
    }
  ],
  "dependencies": {
    "bash-color": "0.0.4",
    "cheerio": "0.20.0",
    "chokidar": "1.5.0",
    "cp": "0.2.0",
    "cpr": "1.1.1",
    "crc": "3.4.0",
    "destroy": "1.0.4",
    "direction": "0.1.5",
    "dom-serializer": "0.1.0",
    "error": "7.0.2",
    "escape-html": "^1.0.3",
    "escape-string-regexp": "1.0.5",
    "extend": "^3.0.0",
    "fresh-require": "1.0.3",
    "front-matter": "^2.1.0",
    "gitbook-asciidoc": "1.2.2",
    "gitbook-markdown": "1.3.2",
    "gitbook-plugin-fontsettings": "2.0.0",
    "gitbook-plugin-highlight": "2.0.2",
    "gitbook-plugin-livereload": "0.0.1",
    "gitbook-plugin-lunr": "1.2.0",
    "gitbook-plugin-search": "2.2.1",
    "gitbook-plugin-sharing": "1.0.2",
    "gitbook-plugin-theme-default": "1.0.7",
    "github-slugid": "1.0.1",
    "graceful-fs": "4.1.4",
    "i18n-t": "1.0.1",
    "ignore": "3.1.2",
    "immutable": "^3.8.1",
    "is": "^3.1.0",
    "js-yaml": "^3.6.1",
    "json-schema-defaults": "0.1.1",
    "jsonschema": "1.1.0",
    "juice": "2.0.0",
    "mkdirp": "0.5.1",
    "moment": "2.13.0",
    "npm": "3.9.2",
    "npmi": "2.0.1",
    "nunjucks": "2.5.2",
    "nunjucks-do": "1.0.0",
    "object-path": "^0.9.2",
    "omit-keys": "^0.1.0",
    "open": "0.0.5",
    "q": "1.4.1",
    "read-installed": "^4.0.3",
    "request": "2.72.0",
    "resolve": "1.1.7",
    "rmdir": "1.2.0",
    "semver": "5.1.0",
    "send": "0.13.2",
    "spawn-cmd": "0.0.2",
    "tiny-lr": "0.2.1",
    "tmp": "0.0.28",
    "urijs": "1.18.0"
  },
  "deprecated": false,
  "description": "Library and cmd utility to generate GitBooks",
  "devDependencies": {
    "eslint": "2.10.2",
    "expect": "^1.20.1",
    "mocha": "^2.4.5"
  },
  "homepage": "https://www.gitbook.com",
  "keywords": [
    "git",
    "book",
    "gitbook"
  ],
  "license": "Apache-2.0",
  "main": "lib/index.js",
  "name": "gitbook",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/GitbookIO/gitbook.git"
  },
  "scripts": {
    "lint": "eslint .",
    "test": "mocha ./testing/setup.js \"./lib/**/*/__tests__/*.js\" --bail --reporter=list --timeout=10000"
  },
  "version": "3.2.3"
}
